### ISSUE TITLE
Unclear how to match the sevsnp report measurment to the binary built in this repo

### ISSUE THREAD

**Issue by ivarprudnikov** [aws/uefi#10]
I've launched m6a.xlarge Amazon Linux instance with AMD sev-snp enabled. 
Installed the dependencies to get the report, then parsed the report (as seen in AWS doc https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snp-attestation.html):

```
[ec2-user@ip-172-31-43-23 sev-guest]$ ./sev-guest-parse-report guest_report.bin 
Version: 2
Guest SVN: 0
Policy: 0x30000
 - Debugging Allowed:       No
 - Migration Agent Allowed: No
 - SMT Allowed:             Yes
 - Min. ABI Major:          0
 - Min. ABI Minor:          0
Family ID:
    00000000000000000000000000000000
Image ID:
    00000000000000000000000000000000
VMPL: 0
Signature Algorithm: 1 (ECDSA P-384 with SHA-384)
Platform Version: 03000000000010207
 - Boot Loader SVN:   3
 - TEE SVN:           0
 - SNP firmware SVN: 10
 - Microcode SVN:    207
Platform Info: 0x3
 - SMT Enabled: Yes
Author Key Enabled: Yes
Report Data:
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
Measurement:
    25ac810f5c4750890fb1a158f097962e04d4d7fb640d1d08
    a99829cf4a70543a47cc6fb192bbe90aa713142361a66155
Host Data:
    0000000000000000000000000000000000000000000000000000000000000000
ID Key Digest:
    000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000
Author Key Digest:
    000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000
Report ID:
    095ff96690717c80615a8feea94e79dfcf008f1c957cd8ab1305c3f049715a15
Migration Agent Report ID:
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
Reported TCB: 03000000000010207
 - Boot Loader SVN:   3
 - TEE SVN:           0
 - SNP firmware SVN: 10
 - Microcode SVN:    207
Chip ID:
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
Signature:
  R:
    77f23faa9c8ac604a9572c9e3e4567e0bf5fc04a0c28255c7755997aeeb6f63c0970254a
    db13e4e7ae4720d96f7aa651000000000000000000000000000000000000000000000000
  S:
    6c72dda0b714d38023631cfc30bb3eaf277ce6cec9bcd93f3ab02e366427cbb97c72eb8e
    31f014b9855357e0fe85ea6f000000000000000000000000000000000000000000000000
```

The measurement indicates a digest (sha384) of the initial boot state `25ac810f5c4750890fb1a158f097962e04d4d7fb640d1d08a99829cf4a70543a47cc6fb192bbe90aa713142361a66155`

The release section has some conflicting info about the hashes though:
-  release `20230421` does not match the measurement
    - indicates digest (in release notes) is `a58211791a556a630a4319dc9e2ea96cc0e9784dd9f20a4fadf81b26c98d163fcdcb6703884bbbb80d7b1de45b3d84d0`
    - if  ovmf_img.fd  is downloaded and then sha384 calculated produces `2bf3363231d8dc2bdff02aca47a6244b258c4fc2903401d896c17d69e2c193d0ed76ff78767c2749ef774b07855aaf28`
- release `20230516` does not match the measurement
    -  indicates digest (in release notes) is `SHA256: c00148b844a508f82f5a62f0c023857892e9b9723c89907e41f5fe0a9488c633` but we need sha384
    - calculated `ovmf_img.fd` is `2707c61c9ad5ecea4b20b1d4df1e2852f5f1bd4b3bc2e43c488f8e0497199c0a55ab784ef9be7fd3d093f271bd042c9d`

Can you elaborate in the readme how to link the measurement to the specific release in this repository?

**Comment by clupuishere** [comment]
Hello! We updated the [README.md](https://github.com/aws/uefi#how-to-generate-a-measurement) with instructions for generating a measurement. Please let us know how it goes after you run the command on your environment.

**Comment by ivarprudnikov** [comment]
Where do you get `ovmf_img.fd` from when calculating the measurement with that python cli mentioned in the readme?

**Comment by mediouni-m** [comment]
Hello,

The flow looks like this:

`
wget https://github.com/aws/uefi/releases/download/20230516/ovmf_img.fd
git clone https://github.com/virtee/sev-snp-measure
./sev-snp-measure/sev-snp-measure.py --mode snp --vcpus=4 --vmm-type=ec2 --ovmf=ovmf_img.fd
`

This will return:

`25ac810f5c4750890fb1a158f097962e04d4d7fb640d1d08a99829cf4a70543a47cc6fb192bbe90aa713142361a66155`

After copying the guest_report.bin and the cek to the machine you're authenticating from, you can run sev-guest-parse-report and also verify that the report is properly signed through the authentication procedure at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snp-attestation.html, through sevtool.

**Comment by ivarprudnikov** [comment]
So I have to try out every release in the repo to find the the value I am looking for? This is fine for now whilst there are only 2 releases.
