### ISSUE TITLE
How to measure the firmware, kernel, initrd, and cmdline 

### ISSUE THREAD

**Issue by w-woloszyn** [aws/uefi#13]
It is not clear to me how one can measure the firmware, kernel, initrd, and cmdline that is running an authentic AMD SEV-SNP Guest VM on AWS. Could you please share a workflow of deployment of the AWS VM and of obtaining and comparing the measurements? (Your repository seems to be related to my question, but I cannot figure out what is the exact workflow.)

**Comment by mediouni-m** [comment]
For firmware attestation, please refer to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snp-attestation.html. The README file in this repository details how to re-create the launch digest from UEFI sources.

To measure kernel, initrd, and cmdline, please use NitroTPM (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nitrotpm.html) to generate a TPM Quote which you can validate through remote attestation.

**Comment by w-woloszyn** [comment]
I appreciate your prompt response.

I have some concerns regarding the proposed solution. Confidential computing is built on the premise that users should not have to place trust in the service provider. However, your solution appears to necessitate trust in both AWS and AMD, as opposed to just AMD, which appears to contradict the core principles of this technology.

A more suitable approach, in my opinion, would involve encoding the kernel, initrd, and cmdline within the OVMF. 

Please feel free to correct me if I am mistaken, but it appears that your solution may not meet the criteria for confidential computing and full attestation.

**Comment by agraf** [comment]
Thank you for your inputs, I'll loop them back to our engineering team.

**Comment by ShannonSD** [comment]
Has there been an update on this issue?
There are a couple of issues I see with the current implementation:
1) The AMD SEV report does not measure the kernel, initrd, and cmdline. 
2) If we use NitroTPM to obtain these measurements, we have no way to verify the quote as there is no publibly available EK certificate for the attached NitroTPM.

In the end, there seems to be no way to measure/attest the guest VM remotely.

**Comment by agraf** [comment]
It is now possible to retrieve the public NitroTPM Endorsement Key for an instance through the AWS API:

  https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-ec2-api-public-endorsement-key-nitrotpm/

**Comment by ShannonSD** [comment]
Thank you for the quick response.
I did see that API but it requires me to have access to the instance and therefore isn't verifiable by a third-party.
There is no link between the SEV report and the TPM quote/key and therefore we cannot bootstrap trust from one to another.
The easiest solution would be if there was a root certificate from AWS that could be used to verify all NitroTPM Endorsement Keys.

**Comment by haraldh** [comment]
Hi @agraf , can I use secure boot with my own keys enrolled with SEV-SNP?

**Comment by haraldh** [comment]
Oh, I see, the variable store is also external and not measured by SEV.

**Comment by agraf** [comment]
Correct, the UEFI Variable Store as well as NitroTPM live outside of SEV-SNP context. Feel free to contact me directly to brainstorm ideas on how to allow workload attestation without trusting hypervisor components.

**Comment by kbindlish** [comment]
hi, is this still the case with AWS EC2 SEV-SNP enabled instances? Do we need NitroTPM to measure the kernel, initrd and cmdline?

**Comment by mediouni-m** [comment]
@kbindlish Still the case.
